
name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        with:
            release: R2020b
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: version          
      - name: Run Tests
        uses: matlab-actions/run-tests@newoptions-bash
        with:
          source-folder: src
          select-by-tag: TestModel
          model-coverage-cobertura: test-results/model-coverage.xml
          test-results-simulink-test: test-results/simulink-test-results.mldatx
          test-results-pdf: test-results/pdf-results.pdf
            
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-artifact
          path: code-coverage/coverage.xml
          
      - name: upload to codecov 
        uses: codecov/codecov-action@v1 
        with:
          file: code-coverage/coverage.xml
