
name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: version          
      # - name: Run Tests
      #   uses: matlab-actions/run-tests@v2
      #   with:
      #     source-folder: src
      #     test-results-junit: test-results/results.xml
      #     code-coverage-cobertura: code-coverage/coverage.xml
      #     test-results-pdf: test-results/results.pdf
      #     test-results-simulink-test: test-results/results.mldatx
      # - name: Run build3
      #   uses: matlab-actions/run-build@v2.4.0
        
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0 
        with:
          tasks: archive1

      - name: Run build2
        uses: matlab-actions/run-build@v2.4.0 
        with:
          tasks: archive2

 

          
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: |
      #       test-results/
      #       code-coverage/
  build2job:
    name: Run MATLAB build2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0 

      
   

    
